# Generated by Django 4.2.16 on 2024-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client_model',
            name='client_name',
            field=models.CharField(max_length=255),
        ),
    ]
