# Generated by Django 4.2.16 on 2024-10-12 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_model',
            old_name='name',
            new_name='project_name',
        ),
    ]
